name: firstworkflow
on: 
  push: 
    branches: 
      - dev
      - 'feature-*'
      - main  
  pull_request:
    branches:
      - main

env:
  ENV_TYPE: DEV
  APP_USER: Dev_user
  APP_Port: 80
  
jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Step1 - pwd ls hostname
        run: |
          pwd
          ls -altr
          hostname
      - name: Step 2 - checkout
        uses: actions/checkout@v6.1.0
      - name: Step 3 - pwd ls hostname
        run: |
          echo `pwd` >> myartifact.txt 
          mkdir artifacts
          echo `ls -altr` >> artifacts/list.txt
          echo `hostname` >> artifacts/hostname.txt
      - name: Step 4 - upload a single file artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: single_file
          path: ./myartifact.txt
  job2:
    name: Job2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: checking current directory
        run:
          pwd
          ls -altr
      - name: download single file artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: single_file
          path: 
      - name: checking the current directory post download
        run: |
          pwd
          ls -altr
      - name: Referring the env variables.
        run: |
          echo "[INFO] Running deployment for $ENV_TYPE with user $APP_USER"
          echo "[INFO] once deployed the application is available in port number $APP_Port"
      - name: Referring Repository Secrets
        run: |
          echo "[INFO] Application passsord is ${{ secrets.APP_PASSWORD }}"
